name: Web Automation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 'stable'

      - name: Use Gradle 7.4
        run: |
          wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
          unzip gradle-7.4-bin.zip
          export PATH=$PWD/gradle-7.4/bin:$PATH
          gradle -v

      - name: Set up Gradle
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradle test